apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: playground
spec:
  selector:
    matchLabels:
      app: playground
      component: frontend
  replicas: {{ .Values.playground.replicas }}
  template:
    metadata:
      labels:
        app: playground
        component: frontend
    spec:
      containers:
      - name: playground
        image: {{ .Values.playground.image.name }}:{{ .Values.playground.image.tag }}
        ports:
        - containerPort: 3000
