apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: playground
  labels:
    app: playground
    component: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    {{ range $host := .Values.playground.ingress.hosts }}
    - host: {{ $host.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: playground
              servicePort: 8000
    {{ end }}
  tls:
    - secretName: kubelego-tls-playground
      hosts:
      - {{ .Values.playground.host }}
