apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pen
  labels:
    app: playground
    component: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
spec:
  rules:
    - host: {{ .Values.playground.host }}
      http:
        paths:
          - path: /
            backend:
              serviceName: playground
              servicePort: 8000
  tls:
    - secretName: kubelego-tls-pen
      hosts:
      - {{ .Values.playground.host }}
