apiVersion: v1
kind: Service
metadata:
  name: playground
  labels:
    app: playground
    component: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: playground
    component: frontend
