dependencies:
 - name: nginx-ingress
   version: 0.4.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 3.0.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 0.3.5
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.1.10
   repository: https://kubernetes-charts.storage.googleapis.com
