apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ovh-mybinder-org
  annotations:
    kubernetes.io/tls-acme: "true"
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: ovh.mybinder.org
      http:
        paths:
          - path: /
            backend:
              serviceName: binder
              servicePort: 8585
  tls:
    - secretName: kubelego-tls-binder-ovh
      hosts:
        - "ovh.mybinder.org"
