version: 0.1.0-183addc

ingress:
  host: beta.mybinder.org

registry:
  prefix: gcr.io/binder-testing/beta-v4-1-

hub:
  url: https://hub.beta.mybinder.org

jupyterhub:
  ingress:
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
    host: hub.beta.mybinder.org

repo2dockerImage: jupyter/repo2docker:v0.4.1

googleAnalyticsCode: "UA-101904940-1"
