version: 0.1.0-a6235f8

service:
  type: ClusterIP


ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  https:
    enabled: true
    type: "kube-lego"

registry:
  enabled: true

jupyterhub:
  proxy:
    service:
      type: ClusterIP
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
    https:
      enabled: true
      type: "kube-lego"
  singleuser:
    memory:
      guarantee: 1G
      limit: 4G

repo2dockerImage: jupyter/repo2docker:v0.4.1
