ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  https:
    enabled: true
    type: "kube-lego"

registry:
  enabled: true

jupyterhub:
  ingress:
    enabled: true
    annotations:
      ingress.kubernetes.io/proxy-body-size: 64m
      kubernetes.io/ingress.class: nginx
    https:
      enabled: true
      type: "kube-lego"
