binderhub:
  ingress:
    host: mybinder.org

  registry:
    prefix: gcr.io/binder-prod/prod-v4-1-

  hub:
    url: https://hub.mybinder.org

  jupyterhub:
    ingress:
      host: hub.mybinder.org

  googleAnalyticsCode: "UA-101904940-1"

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 35.202.202.188

redirector:
  redirects:
    - type: host
      host:
        from: beta.mybinder.org
        to: mybinder.org
    - type: host
      host:
        from: docs.mybinder.org
        to: mybinder.readthedocs.io
