version: 0.1.0-183addc

ingress:
  host: binder.binder-staging.omgwtf.in

service:
  type: ClusterIP

registry:
  prefix: gcr.io/binder-testing/stage-v04-1-

hub:
  url: https://hub.binder-staging.omgwtf.in

jupyterhub:
  proxy:
    service:
      type: ClusterIP
  ingress:
    host: hub.binder-staging.omgwtf.in

repo2dockerImage: jupyter/repo2docker:v0.4.1
