binderhub:
  ingress:
    host: staging.mybinder.org

  registry:
    prefix: gcr.io/binder-staging/image-v0-4-

  hub:
    url: https://hub.staging.mybinder.org

  jupyterhub:
    ingress:
      host: hub.staging.mybinder.org

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 104.197.11.66
