binderhub:
  ingress:
    host: staging.mybinder.org

  registry:
    prefix: gcr.io/binder-staging/image-v0-4-

  hub:
    url: https://hub.staging.mybinder.org

  jupyterhub:
    ingress:
      host: hub.staging.mybinder.org

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 104.197.11.66

redirector:
  redirects:
    - type: host
      host:
        from: beta.staging.mybinder.org
        to: staging.mybinder.org
    - type: host
      host:
        from: docs.staging.mybinder.org
        to: mybinder.readthedocs.io
