binderhub:
  ingress:
    hosts:
      - staging.mybinder.org

  registry:
    prefix: gcr.io/binder-staging/r2d-05168b0-

  build:
    appendix: |
      USER root
      ENV BINDER_URL={binder_url}
      ENV REPO_URL={repo_url}
      RUN cd /tmp \
       && wget -q https://github.com/jupyterhub/mybinder.org-deploy/archive/329ab6a52c272cf425f9bd69221bf072893f87b1.tar.gz -O appendix.tar.gz \
       && tar --wildcards -xzf appendix.tar.gz --strip 1 */appendix\
       && ./appendix/run-appendix \
       && rm -rf appendix.tar.gz appendix
      USER $NB_USER

  hub:
    url: https://hub.staging.mybinder.org

  jupyterhub:
    singleuser:
      memory:
        guarantee: 256M
        limit: 256M
    ingress:
      hosts:
        - hub.staging.mybinder.org
      tls:
        - secretName: kubelego-tls-jupyterhub-staging
          hosts:
            - hub.staging.mybinder.org

grafana:
  server:
    ingress:
      hosts:
        - grafana.staging.mybinder.org
      tls:
        - hosts:
            - grafana.staging.mybinder.org
          secretName: kubelego-tls-grafana

prometheus:
  server:
    ingress:
        hosts:
          - prometheus.staging.mybinder.org
        tls:
          - hosts:
              - prometheus.staging.mybinder.org
            secretName: kubelego-tls-prometheus

nginx-ingress:
  controller:
    service:
      loadBalancerIP: 104.197.11.66
    replicaCount: 4

static:
  ingress:
    hosts:
      - static.staging.mybinder.org

redirector:
  redirects:
    - type: host
      host:
        from: beta.staging.mybinder.org
        to: staging.mybinder.org
    - type: host
      host:
        from: docs.staging.mybinder.org
        to: mybinder.readthedocs.io
    - type: host
      host:
        from: playground.staging.mybinder.org
        to: play.nteract.io
