ingress:
  host: staging.mybinder.org

registry:
  prefix: gcr.io/binder-testing/stage-v04-1-

hub:
  url: https://hub.staging.mybinder.org

jupyterhub:
  ingress:
    host: hub.staging.mybinder.org

