version: 0.1.0-183addc

ingress:
  host: staging.mybinder.org

service:
  type: ClusterIP

registry:
  prefix: gcr.io/binder-testing/stage-v04-1-

hub:
  url: https://hub.staging.mybinder.org

jupyterhub:
  proxy:
    service:
      type: ClusterIP
  ingress:
    host: hub.staging.mybinder.org

repo2dockerImage: jupyter/repo2docker:v0.4.1
