# minimal content for fields required in secret config
# for use when linting/testing PRs prior to merge
binderhub:
  networkPolicy:
    egress:
      bannedIps:
        - "1.1.1.1/32"
    ingress:
      bannedIps:
        - "1.1.1.1/32"
  jupyterhub:
    hub:
      services:
        binder:
          apiToken: "abc123"
    proxy:
      secretToken: "abc123"
matomo:
  db:
    serviceAccountKey: "abc123"

analyticsPublisher:
  serviceAccountKey: "abc123"
