projectName: turing

tags:
  kubelego: false
  certmanager: true

letsencrypt:
  contactEmail: drsarahlgibson@gmail.com

binderhub:
  config:
    BinderHub:
      pod_quota: 0
      hub_url: https://hub.mybinder.turing.ac.uk
      badge_base_url: https://mybinder.org
      sticky_builds: true
      # Docker Hub registry for Turing
      use_registry: true
      image_prefix: turingmybinder/binder-prod-

  replicas: 1

  resources:
    requests:
      cpu: "0.25"
      memory: 1Gi
    limits:
      cpu: "2"
      memory: 1Gi

  ingress:
    enabled: true
    hosts:
      - binder.mybinder.turing.ac.uk
      - turing.mybinder.org
    annotations:
      kubernetes.io/ingress.class: nginx
      https:
        enabled: true
        type: nginx
    tls:
      - secretName: turing-binder-tls-crt
        hosts:
          - binder.mybinder.turing.ac.uk
          - turing.mybinder.org

  extraVolumes:
    - name: event-secret
      secret:
        secretName: events-archiver-secret
  extraVolumeMounts:
    - name: event-secret
      mountPath: /event-secret
      readOnly: true
  extraEnv:
    - name: GOOGLE_APPLICATION_CREDENTIALS
      value: /event-secret/service-account.json

  jupyterhub:
    hub:
      resources:
        requests:
          cpu: "0.25"
          memory: 1Gi
        limits:
          cpu: "2"
          memory: 1Gi
    singleuser:
      memory:
        guarantee: 550M
        limit: 2G
      cpu:
        guarantee: 0.01
        limit: 1
    proxy:
      chp:
        resources:
          requests:
            memory: 320Mi
            cpu: "0.1"
          limits:
            memory: 320Mi
            cpu: "0.5"
      nginx:
        resources:
          requests:
            memory: 512Mi
            cpu: "0.25"
          limits:
            memory: 512Mi
            cpu: 1

    ingress:
      enabled: true
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: "true"
        https:
          enabled: true
          type: nginx
      hosts:
        - hub.mybinder.turing.ac.uk
      tls:
        - secretName: turing-hub-tls-crt
          hosts:
            - hub.mybinder.turing.ac.uk

    scheduling:
      userScheduler:
        enabled: false
      podPriority:
        enabled: true
      userPlaceholder:
        enabled: true
        replicas: 5

  imageCleaner:
    # Use 40GB as upper limit, size is given in bytes
    imageGCThresholdHigh: 40e9
    imageGCThresholdLow: 30e9
    imageGCThresholdType: "absolute"

grafana:
  ingress:
    annotations:
      kubernetes.io/ingress.class: nginx
      kubernetes.io/tls-acme: 'true'
    hosts:
      - grafana.mybinder.turing.ac.uk
    tls:
      - secretName: turing-grafana-tls-crt
        hosts:
          - grafana.mybinder.turing.ac.uk

  datasources:
    datasources.yaml:
      apiVersion: 1
      datasources:
        - name: prometheus
          orgId: 1
          type: prometheus
          url: https://prometheus.mybinder.turing.ac.uk
          access: direct
          isDefault: true
          editable: false

prometheus:
  server:
    ingress:
      annotations:
        kubernetes.io/ingress.class: nginx
        kubernetes.io/tls-acme: 'true'
      hosts:
        - prometheus.mybinder.turing.ac.uk
        - prometheus.turing.mybinder.org
      tls:
        - hosts:
            - prometheus.mybinder.turing.ac.uk
            - prometheus.turing.mybinder.org
          secretName: turing-prometheus-tls-crt


nginx-ingress:
  controller:
    service:
      loadBalancerIP: 51.105.120.231
    config:
      proxy-body-size: 64m


static:
  ingress:
    hosts:
      - static.mybinder.turing.ac.uk
    tls:
      secretName: turing-static-tls-crt

redirector:
  redirects:
    - type: host
      host:
        from: docs-mybinder.turing.10.0.0.1.xip.io
        to: mybinder.readthedocs.io

matomo:
  enabled: false
  db:
    instanceName: binder-staging:us-central1:matomo
    serviceAccountKey: ""
  trustedHosts:
    - staging-mybinder.turing.10.0.0.1.xip.io
  ingress:
    hosts:
      - staging-mybinder.turing.10.0.0.1.xip.io

analyticsPublisher:
  enabled: false
  project: binder-turing
  events:
    sourceBucket: mybinder-staging-events-raw-export
    destinationBucket: mybinder-staging-events-archive

gcsProxy:
  enabled: false
  buckets:
    - name: mybinder-staging-events-archive
      host: archive-analytics-staging-mybinder.turing.10.0.0.1.xip.io

cert-manager:
  ingressShim:
    defaultIssuerName: "letsencrypt-prod"
    defaultIssuerKind: "ClusterIssuer"
    defaultACMEChallengeType: "http01"
