{{- if .Values.gcsProxy.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: gcs-proxy
  labels:
    app: gcs-proxy
    component: nginx
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: gcs-proxy
    component: nginx
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
{{- end }}