jupyterhub:
  proxy:
    secretToken: d954cc5a15c740ba738f48b9d36f1dc2aac3e7f151ca9c859330aa928755cb0f

  hub:
    cookieSecret: a38d32115fdce314d01f0369b3ac90fece93715f6e07806715061687163da09f
    services:
      binder:
        admin: true
        apiToken: e01b8f566f4e061f26a79f47d0a326f184364912714eafb6ae0d69c9e2287ede

registry:
  password: |
    {
      "type": "service_account",
      "project_id": "binder-staging",
      "private_key_id": "8ae36a5cd3d18068b9fa1a5762954ca8387df21c",
      "private_key": "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQC5SJJKAB6ppu2J\niuwOb6nvXExKrXuxvEGa+iOi+WwFIpPYA6dgLb9GbBATBgDrFcqDQaiCWZOldVwD\nSTnc+0fQr+nsiaCO6mnC9iNkvUienHuoQTnqsUyaTBklwQedw11jQ4lG+2V6tmXp\n0oUZ2eS/OvQON22uP4+zLEJaumFLtd6PTU+3T8km2n+vkwO2WAXuk2hnEX3VW8py\n/jmATBwWOKwxO5vs/FaA3Nw7ZEIDnu3WWTvKypCFdOELZYJQ1ypEYnkkIYMoc9GF\n7UCb+7V5aj25Zj9B4VWHX3l4dGomGmzQFSJrN/Py5EG/dR98Zeu8evtw6T9isTAr\ntEG5nTUhAgMBAAECggEABjYVmV95p6xN6D98/Frn8ntAn3xDWkj6Vgyupyb/ZQis\ntiAhO0stT1oOC+U2oKrhWBcaZAxGs9REWmPZCbxuwuMyz1gpxsC6/OstcpIZ3h9W\n0eQl4eVBsSZ97VMUQ0iqV8qKzpNc6ok0z2rcRWqVjYeXaOaYya+dzJ7eNpZq7pPC\nl5Vit4QigNQH73PYDVyx3qzDK7UG6QLzGpYBMkB6hhEAFJlXS0KM3eEdVWQRbqhh\ncAwwG4gO6mIpYeR+EdiTypX8ib1MggjyyTq0a/nEg40sGpSVaajCZyisxphfoQAG\ny4htoJkTtFo2JBzlrksUp5WO3aFkyBqFtCgS92CRlQKBgQDp4uXq+QUwrSozGNhb\nWrWJZOO4SfVDRlKqsolNlktzcM07kpKZg4bgVg5Ls29WwlEQw0aTURz+fcsfSvzQ\nuMl/IBFhrFNFNQFqvqiai7znxksA0lXGEaCxs2Vxdbf/0LB3r+jXxQqJdlfV0MHl\nfOlJxm+saf9MF512WHg8Id7/nwKBgQDKzUQNXOVV1CoXv2vUYSQIUmGE8hcldrLi\nSDFdJOJjmfB91WBtqL+r81gnIsSzAbRkbH1CFa6u/hlpp3zbRQOSxQb4CfGi0hF5\nwDg4r6BGnOcdPL6s5WzLdIkg6j+1y/Ub+qByJbAAok/Fu8Z6EC1nRdZa4+1IEFB0\n4Ze19IyTPwKBgCEC13S8xRDDwCsKHK94NBs6VDHUrntaV5ykKmD7D5cxmqYH4A0u\n1UCgpM/meZaDQrHc/f8Y+cCpvJukF97V1grNWeaxTed8vcB1PJLjmjwUbs2k4lpc\nbpPmQDEtblT6/Y1HFNQviXcxbuBM4LElWkABdA2fwFrbEmx7vCywkyr9AoGBAKLr\nnhUCIPb/l8U2MYEPfOv2ioNMHQ4qunCQwJ9sZzbOz2W3ilzuKPURbCscglqwLuRS\nR5pUYt4QIgg/1k0stz8sa3nOO0GrcwCVTFU1uhOgLwbM6v1o3irgdt1rcj0xGbsd\nb9Hjtu37dwyJ2lvrLR5++0JPQysWeBw9sywoxtnvAoGAZb15BRVN6N93FpLzuyHI\nmERt4HZiW6iNPXVifEx0t1/NhzOHAzp97xM7AZ7VAOFVgtB55SDXGk9bSUAP8ovl\nyR7QN237011EyLezgzf1mIEGoFFo8OAJ8fCIrHTmVj1MW1ZMieG5v4upFv3kfkix\nvGmIqo6ck9DEpsK0pt6hgX4=\n-----END PRIVATE KEY-----\n",
      "client_email": "binderhub-builder@binder-staging.iam.gserviceaccount.com",
      "client_id": "116452528563575511476",
      "auth_uri": "https://accounts.google.com/o/oauth2/auth",
      "token_uri": "https://accounts.google.com/o/oauth2/token",
      "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
      "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/binderhub-builder%40binder-staging.iam.gserviceaccount.com"
    }
