apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: analytics-publisher
  labels:
    app: analytics-publisher
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      app: events-archiver
