{{- if .Values.analyticsPublisher.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: events-archiver
  labels:
    app: events-archiver
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  minAvailable: 0
  selector:
    matchLabels:
      release: {{ .Release.Name }}
      heritage: {{ .Release.Service }}
      app: analytics-publisher
{{- end }}