{{- if .Values.proxyPatches.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-patches-nginx-config
data:
  redirects.conf: |
    server {
      listen 80;

      # Return 404 for anything that comes here
      # This preserves the same behavior as before, just without overloading the hub
      location / {
        return 404;
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-help-config
data:
  routes.json: {{ toJson .Values.proxyPatches.routes | quote }}
{{- end }}
