{{- if .Values.proxyPatches.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-patches-nginx-config
data:
  redirects.conf: |
    server {
      listen 80;

      # we want to redirect *humans* to the landing page,
      # but not stale API requests from clients
      if ($request_method != GET) {
        # 404 on anything but a GET request
        return 404;
      }
      location ~ ^/user/.*/api/ {
        # 404 on API requests
        # these can happen when a pod has been culled
        # but clients are still connected and trying to poll
        return 404;
      }
      location / {
        rewrite (.*) https://{{ index .Values.binderhub.ingress.hosts 0 }} redirect;
      }
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-help-config
data:
  routes.json: {{ toJson .Values.proxyPatches.routes | quote }}
{{- end }}
