{{- if .Values.proxyPatches.enabled }}
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-patches-config
data:
  redirects.conf: |
    server {
          listen 80;
          rewrite (.*) https://{{ index .Values.binderhub.ingress.hosts 0 }} redirect;
    }

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: proxy-help-config
data:
  routes.json: |
    {
      "/user": "service:proxy-patches"
    }
{{- end }}
