apiVersion: v1
kind: Service
metadata:
  name: proxy-patches
  labels:
    app: proxy-patches
    component: proxy-patches
spec:
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: proxy-patches
    component: proxy-patches
