apiVersion: apps/v1
kind: Deployment
metadata:
  name: events-archiver
  labels:
    app: events-archiver
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: events-archiver
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: events-archiver
        heritage: {{ .Release.Service }}
        release: {{ .Release.Name }}
    spec:
      volumes:
      - name: secrets
        secret:
          secretName: events-archiver-secrets
      containers:
      - name: events-archiver
        image: {{ .Values.eventsArchiver.image.name}}:{{ .Values.eventsArchiver.image.tag }}
        env:
          - name: GOOGLE_APPLICATION_CREDENTIALS
            value: /secrets/service-account.json
          - name: PROJECT_NAME
            value: {{ .Values.projectName }}
          - name: SOURCE_BUCKET
            value: {{ .Values.eventsArchiver.sourceBucket | quote }}
          - name: DESTINATION_BUCKET
            value: {{ .Values.eventsArchiver.destinationBucket | quote }}
        volumeMounts:
          - name: secrets
            mountPath: /secrets
            readOnly: true
