ingress:
  host: binder.binder-staging.omgwtf.in

registry:
  prefix: gcr.io/binder-testing/staging-

hub:
  url: https://hub.binder-staging.omgwtf.in

jupyterhub:
  ingress:
    host: hub.binder-staging.omgwtf.in

repo2dockerImage: jupyter/repo2docker:v0.2.5
