apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: matomo
  labels:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:

  minAvailable: 0
  selector:
    matchLabels:
      app: matomo
      heritage: {{ .Release.Service }}
      release: {{ .Release.Name }}
