{{- if .Values.matomo.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: cloudsql-instance-credentials
  labels:
    app: matomo
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
type: Opaque
data:
  credentials.json: {{ .Values.matomo.db.serviceAccountKey | b64enc | quote }}
{{- end }}
