dependencies:
 - name: nginx-ingress
   version: 0.8.13
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   # Pin to 5.2.x until https://github.com/kubernetes/charts/pull/3546#issuecomment-367542705 is sorted
   version: 5.2.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 0.6.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.1.12
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: binderhub
   version: 0.1.0-100220a
   repository: https://jupyterhub.github.io/helm-chart
