dependencies:
 - name: ingress-nginx
   version: 2.13.0
   repository: https://kubernetes.github.io/ingress-nginx
 - name: prometheus
   version: 11.0.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 3.10.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: binderhub
   version: 0.2.0-n242.h87e78af
   repository: https://jupyterhub.github.io/helm-chart
