dependencies:
 - name: nginx-ingress
   version: 0.20.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 6.2.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 1.2.0
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.4.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: binderhub
   version: 0.1.0-0d4acbd
   repository: https://jupyterhub.github.io/helm-chart
