dependencies:
 - name: nginx-ingress
   version: 1.40.3
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: prometheus
   version: 11.0.2
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: grafana
   version: 3.10.1
   repository: https://kubernetes-charts.storage.googleapis.com
 - name: kube-lego
   version: 0.4.2
   repository: https://kubernetes-charts.storage.googleapis.com
   tags:
     - kubelego
 - name: cert-manager
   version: v0.12.0
   repository: https://charts.jetstack.io
   tags:
     - certmanager
 - name: binderhub
   version: 0.2.0-n187.hdb3aa0e
   repository: https://jupyterhub.github.io/helm-chart
