name: Lint and Validate helm chart

on:
  pull_request:
    paths:
      - "**/*.yaml"
      - "**/*.yml"

env:
  HELM_VERSION: "v2.16.10"

jobs:
  lint-config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install yamllint

      # We use --no-warnings in this step to reduce output to critical errors
      - name: Run yamllint on everything but secrets
        run: |
          yamllint -d scripts/yamllint-no-secrets.yaml --no-warnings .

      - name: Unlock git-crypt secrets
        if: github.event.pull_request.head.repo.fork == false
        uses: sliteteam/github-action-git-crypt-unlock@a09ea5079c1b0e1887d4c8d7a4b20f00b5c2d06b
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      # We use --no-warnings in this step to reduce output to critical errors
      - name: Run yamllint on secrets
        if: github.event.pull_request.head.repo.fork == false
        run: |
          yamllint -d scripts/yamllint-config.yaml --no-warnings secrets/

  lint-helm:
    if: github.event.pull_request.head.repo.fork == false
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        release: ["staging", "prod", "ovh", "turing"]
        kube_version: ["1.15", "1.18"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install chartpress

      - name: Install helm
        run: |
          curl -L https://storage.googleapis.com/kubernetes-helm/helm-${{ env.HELM_VERSION }}-linux-amd64.tar.gz | tar --directory ${HOME} --extract --gzip --file -
          sudo mv ${HOME}/linux-amd64/helm /usr/local/bin/helm

      - name: Install helm kubeval plugin
        run: |
          helm plugin install https://github.com/instrumenta/helm-kubeval

      - name: Install local charts
        working-directory: mybinder
        run: |
          helm init --client-only
          helm dep up
          helm plugin install https://github.com/instrumenta/helm-kubeval

      - name: Unlock git-crypt secrets
        uses: sliteteam/github-action-git-crypt-unlock@a09ea5079c1b0e1887d4c8d7a4b20f00b5c2d06b
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}

      - name: Run chartpress
        run: |
          chartpress

      - name: Run helm kubeval for ${{ matrix.release }} with kube-${{ matrix.kube_version }}
        run: |
          helm kubeval \
          --kubernetes-version ${{ matrix.kube_version }} \
          --strict \
          --ignore-missing-schemas \
          -f secrets/config/common.yaml \
          -f config/${{ matrix.release }}.yaml \
          -f secrets/config/${{ matrix.release }}.yaml
          mybinder
